### ISSUE TITLE
Ensure that there are no more major bugs in the library

### ISSUE THREAD

**Issue by gentauro** [spisemisu/elm-sha#1]
In order to ensure that there are **no** more **major bugs** in the library, I would need an extra pair of eyes to look the code through:

Source: [Fixed major bug where every chunks last values were set to penultimate and last values.](https://github.com/spisemisu/elm-sha/commit/7de82ebe2653c0da41a7c12a1ffd8a355f22409d)

**Comment by gentauro** [comment]
It might be people used to work with the SHA-1 and SHA-2 algorithms that knows **corner test cases** to ensure the library works correctly.

> **Note**: Functional background (Elm or Haskell) might be useful.

**Comment by gentauro** [comment]
@chrisveness I found a _nasty_ bug in my `Elm` code which is a port (I have combined both the `SHA-1` and `SHA-256` together into the same _code_) of your libraries.

You might have some useful input on how to do **corner test cases** to ensure correctness and that would be really helpful.

Thank you in advance.

> Note: It was a pleasure to port your code from `JavaScript` to `Elm`

**Comment by gentauro** [comment]
Feedback from [Elm on slack](https://elmlang.slack.com/messages/general/):

> rohan [10:35 AM] 
> @gentauro have you considered writing a fuzz test to compare output between native and your implementation? i imagine that would be a really good way of checking it’s working as desired.

> rohan [10:43 AM]  
> fuzz test is another word for property-based testing (like haskell’s quickcheck) it generates hundreds of random test cases to check your code and shrinks any failures to their simplest case.


> rohan [10:44 AM]  
> yes
> [10:44]  
> looks like you need to update elm-test
> [10:44]  
> http://package.elm-lang.org/packages/elm-community/elm-test/2.1.0/Fuzz

> gentauro [10:49 AM]  
> I just need to hook it up with a port right? So I can run the native `window.crypto || window.msCrypto`
> rohan [10:49 AM]  
> @gentauro i imagine, yes

[elm-test Fuzz](http://package.elm-lang.org/packages/elm-community/elm-test/latest/Fuzz)

**Comment by chrisveness** [comment]
@gentauro I would be open to adding more complete tests. I had some trouble tracking down NIST tests, as [www.nsrl.nist.gov/testdata](http://www.nsrl.nist.gov/testdata/) has dead links, but I eventually located them at [csrc.nist.gov/groups/STM/cavp/secure-hashing.html#test-vectors](http://csrc.nist.gov/groups/STM/cavp/secure-hashing.html#test-vectors).

NIST say these tests provide for 'informal' verification (as opposed to full CAVP validation), but would hopefully provide reasonable confidence.

Unfortunately those `.rsp`-format tests work off hex-encoded byte streams rather than UTF-8 strings, so some restructuring of my library will be required to take advantage of them. I've been considering a revision to bring the libraries up-to-date with ES2015 (including ES modules), so I'll incorporate those tests when I do. If I'm too tardy for you, you might like to look at those `.rsp` test vectors for youself.

**Comment by gentauro** [comment]
@chrisveness thank you very much for the link!!! I can see that I can test (only bytes, not bit) the `.rsp` files on my Linux box like this:
```
mon@razerRamon:~/spiseMisu/code/elm-sha/app/shabytetestvectors$ more SHA256ShortMsg.rsp 
#  CAVS 11.0
#  "SHA-256 ShortMsg" information
#  SHA-256 tests are configured for BYTE oriented implementations
#  Generated on Tue Mar 15 08:23:38 2011

[L = 32]

Len = 0
Msg = 00
MD = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Len = 8
Msg = d3
MD = 28969cdfa74a12c82f3bad960b0b000aca2ac329deea5c2328ebc6f2ba9802c1

...

Len = 72
--More--(10%)

mon@razerRamon:~/spiseMisu/code/elm-sha/app/shabytetestvectors$ echo -n '0' | xxd -r -p | sha256sum 
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
mon@razerRamon:~/spiseMisu/code/elm-sha/app/shabytetestvectors$ echo -n 'd3' | xxd -r -p | sha256sum 
28969cdfa74a12c82f3bad960b0b000aca2ac329deea5c2328ebc6f2ba9802c1  -
```
So i guess what's needed for my library (and yours) is to create a `xxd` tool that takes a hexdump into bytes.

Once again thank you for your code :+1:

**Comment by chrisveness** [comment]
I've updated my Sha1 hash routine to take options for message format and output format (local copy, not yet on github).

If the message format is 'hex-bytes', I apply the following function to the message:

    function hexBytesToString(hexStr) {
        hexStr = hexStr.replace(' ', ''); // allow space-separated groups
        let str = '';
        for (let i=0; i<hexStr.length; i+=2) {
            str += String.fromCharCode(parseInt(hexStr.slice(i, i+2), 16));
        }
        return str;
    }

I can now do tests using the `.rsp` test vectors: my SHA-1 tests (using [chai](http://chaijs.com/)) are:

    // csrc.nist.gov/publications/fips/fips180-2/fips180-2.pdf Appendex A: SHA-1 Examples
    const msg1 = 'abc';
    it('checks FIPS 180-2 A.1', function() { Sha1.hash(msg1, { outFormat: 'hex-8' }).should.equal('a9993e36 4706816a ba3e2571 7850c26c 9cd0d89d'); });
    const msg2 = 'abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq';
    it('checks FIPS 180-2 A.2', function() { Sha1.hash(msg2, { outFormat: 'hex-8' }).should.equal('84983e44 1c3bd26e baae4aa1 f95129e5 e54670f1'); });
    const msg3 = 'a'.repeat(1000000);
    it('checks FIPS 180-2 A.3', function() { Sha1.hash(msg3, { outFormat: 'hex-8' }).should.equal('34aa973c d4c4daa4 f61eeb2b dbad2731 6534016f'); });

    // csrc.nist.gov/groups/STM/cavp/secure-hashing.html#test-vectors
    const sha1ShortMsg = fs.readFileSync('./test/SHA1ShortMsg.rsp', 'utf8');
    const msgS = sha1ShortMsg.split('\r\n').filter(line => line.slice(0,6) == 'Msg = ').map(line => line.slice(6));
    const mdS = sha1ShortMsg.split('\r\n').filter(line => line.slice(0,5) == 'MD = ').map(line => line.slice(5));
    for (let t=0; t<msgS.length; t++) {
        if (msgS[t] == '00') msgS[t] = ''; // what are NIST up to? '00'.length == 0? duh!
        it('checks sha1ShortMsg Len '+msgS[t].length, function() { Sha1.hash(msgS[t], { msgFormat: 'hex-bytes' }).should.equal(mdS[t]); });
    }
    const sha1LongMsg = fs.readFileSync('./test/SHA1LongMsg.rsp', 'utf8');
    const msgL = sha1LongMsg.split('\r\n').filter(line => line.slice(0,6) == 'Msg = ').map(line => line.slice(6));
    const mdL = sha1LongMsg.split('\r\n').filter(line => line.slice(0,5) == 'MD = ').map(line => line.slice(5));
    for (let t=0; t<msgL.length; t++) {
        it('checks sha1LongMsg Len '+msgL[t].length, function() { Sha1.hash(msgL[t], { msgFormat: 'hex-bytes' }).should.equal(mdL[t]); });
    }

It would be interesting to check whether these tests would have caught your original bug: I hope so!

**Comment by gentauro** [comment]
Wow, that's sounds pretty impressive :+1: 

I will update my code to support hex as well as soon as I can (see **Note** below). Btw is there anyway to test  for `HEX` vs. `UTF-8` vs. `Unicode`? I mean, could this be done by testing for some values in the text? I had to port your **Unicode** -> **UTF-8** and **UTF-8** -> **Unicode** as `Elm` have not implemented `escape` and `unescape` due to being deprecated:

- [Deprecated and obsolete features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features)

> The `escape` and `unescape` functions are deprecated. Use `encodeURI`, `encodeURIComponent`, `decodeURI` or `decodeURIComponent` to encode and decode escape sequences for special characters.

But I can see in those functions, that you check for some values in order to replace them. I think it will be possible to add a few extra functions `isUnicode`, `isUTF8` and `isHex` that will tell which kind of string you are working with and then based on that (`switch`/`case`), it will choose the right function to modify the string before it's sent to `shaXXXsum`.

- [UTF8.elm](https://github.com/spisemisu/elm-utf8/blob/1.0.0/src/UTF8.elm#L35-L69)

> **Note**: At the moment, I'm working on my `Merkle Tree` in `Elm` (the reason I ported `SHA` in the first place):

```

Merkle Tree of Json Values: {
    "count": 6,
    "hash": "14f8fd6",
    "left": {
        "count": 4,
        "hash": "4bacec6",
        "left": {
            "count": 2,
            "hash": "111a9fe",
            "left": {
                "hash": "5130e55",
                "data": {
                    "name": "Bridge Cafe",
                    "rating": 4,
                    "date": "2014-02-20T00:00:00.0000000Z"
                }
            },
            "right": {
                "hash": "9fdce19",
                "data": {
                    "name": "Prima Doner",
                    "rating": 2,
                    "date": "2014-04-15T00:00:00.0000000Z"
                }
            }
        },
        "right": {
            "count": 2,
            "hash": "56a8994",
            "left": {
                "hash": "3238271",
                "data": {
                    "name": "The Bull",
                    "rating": 3,
                    "date": "2014-06-05T00:00:00.0000000Z"
                }
            },
            "right": {
                "hash": "b54b483",
                "data": {
                    "name": "The Tall Ship",
                    "rating": 5,
                    "date": "2014-10-30T00:00:00.0000000Z"
                }
            }
        }
    },
    "right": {
        "count": 2,
        "hash": "1eee38b",
        "left": {
            "count": 2,
            "hash": "fdd4753",
            "left": {
                "hash": "916ee1e",
                "data": {
                    "name": "Roy's Rolls",
                    "rating": 3,
                    "date": "2015-01-10T00:00:00.0000000Z"
                }
            },
            "right": {
                "hash": "7ff4830",
                "data": {
                    "name": "Prima Doner",
                    "rating": 4,
                    "date": "2015-02-12T00:00:00.0000000Z"
                }
            }
        },
        "right": null
    }
}
```
[Technology at GDS’s Blog: Guaranteeing the integrity of a register](https://gdstechnology.blog.gov.uk/2015/10/13/guaranteeing-the-integrity-of-a-register/)

**Comment by gentauro** [comment]
> It would be interesting to check whether these tests would have caught your original bug: I hope so!

I will for sure give it a test on my [1.0.2](http://package.elm-lang.org/packages/spisemisu/elm-sha/1.0.2) :+1:

**Comment by chrisveness** [comment]
Updated tests using `rsp` test vectors are now on github.

The message format has to be passed as an option: there can be no way to determine automatically whether e.g. '1234' should be interpreted as a string or as hex digits. I'm not sure how much value there is in the message format option beyond testing, but there may be value I'm not aware of.

The `unescape(encodeURIComponent())` is very JavaScript-specific, it just happens to be convenient to leverage those functions. I think Unicode string handling varies significantly between languages; in JavaScript, all strings can be considered as being UTF-16. If you need to do UTF-8 encoding from scratch, [github.com/mathiasbynens/utf8.js](https://github.com/mathiasbynens/utf8.js) looks a good reference, though something like [gist.github.com/chrisveness/bcb00eb717e6382c5608](https://gist.github.com/chrisveness/bcb00eb717e6382c5608) could be sufficient.

**Comment by gentauro** [comment]
The way I handle what is `HEX` and what isn't is by checking if a text is prefixed with `0x` :+1: 

Btw, as `Elm` haven't really ported `parseInt` to handle `radix` I had to write my own:

```
-- HELPERS


isHex : String -> String
isHex str =
    case String.startsWith "0x" str of
        True ->
            hexToString (String.dropLeft 2 str)

        False ->
            toSingleByte str


hexToString : String -> String
hexToString hex =
    -- Take chunks of 2 hex digits and apply formula: (a * 16^1) + (b * 16^0)
    -- Example (d_16 = 13_10): 0xd3 => (d * 16^1) + (3 * 16^0) = 208 + 3 = 211
    let
        asciiToNumber x =
            let
                y =
                    x |> Char.toCode
            in
                case y > 96 of
                    -- ASCII codes for [a-f] => [97-102]
                    True ->
                        y - 97 + 10

                    -- ASCII codes for [0-9] => [48-57]
                    False ->
                        y - 48

        rec xs acc =
            case xs == "" of
                False ->
                    let
                        ( y, ys ) =
                            case String.uncons xs of
                                Nothing ->
                                    ( Nothing, "" )

                                Just ( a, rest ) ->
                                    ( Just a, rest )

                        ( z, zs ) =
                            case String.uncons ys of
                                Nothing ->
                                    ( Nothing, "" )

                                Just ( b, rest ) ->
                                    ( Just b, rest )

                        keyCode =
                            case ( y, z ) of
                                ( Just a, Just b ) ->
                                    ((asciiToNumber a) * 16)
                                        + (asciiToNumber b)

                                ( Just a, _ ) ->
                                    (asciiToNumber a) * 16

                                ( _, _ ) ->
                                    0

                        str =
                            case keyCode of
                                0 ->
                                    ""

                                _ ->
                                    keyCode |> stringify
                    in
                        rec zs (acc ++ str)

                True ->
                    acc
    in
        rec (hex |> String.toLower) ""
```

which is probably failing somewhere:
```
mon@razerRamon:~/spiseMisu/code/elm-sha/tests$ ./run-tests.sh 
Success! Compiled 2 modules.                                        
Successfully generated test.js
/home/mon/spiseMisu/code/elm-sha/tests/test.js:567
		throw new Error(
		^

Error: Ran into a `Debug.crash` in module `ElmTest.Runner.Console`

This was caused by the `case` expression between lines 28 and 33.
One of the branches ended with a crash and the following value got through:

    False

The message provided by the code author is:

      5 suites run, containing 74 tests
  3 suites and 69 tests passed
  2 suites and 5 tests failed

Test Suite: Tests for SHA cryptographic hash library: FAILED
  Test Suite: SHA-1 Hashing: all tests passed
  Test Suite: SHA-224 Hashing: all tests passed
  Test Suite: SHA-256 Hashing: all tests passed
  Test Suite: SHA-1 Short Msg (RSP): FAILED
    0x00: passed.
    0x36: passed.
    0x195a: passed.
    0xdf4bd2: passed.
    0x549e959e: passed.
    0xf7fb1be205: passed.
    0xc0e5abeaea63: passed.
    0x63bfc1ed7f78ab: passed.
    0x7e3d7b3eada98866: passed.
    0x9e61e55d9ed37b1c20: passed.
    0x9777cf90dd7c7e863506: passed.
    0x4eb08c9e683c94bea00dfa: passed.
    0x0938f2e2ebb64f8af8bbfc91: passed.
    0x74c9996d14e87d3e6cbea7029d: passed.
    0x51dca5c0f8e5d49596f32d3eb874: passed.
    0x3a36ea49684820a2adc7fc4175ba78: passed.
    0x3552694cdf663fd94b224747ac406aaf: passed.
    0xf216a1cbde2446b1edf41e93481d33e2ed: passed.
    0xa3cf714bf112647e727e8cfd46499acd35a6: passed.
    0x148de640f3c11591a6f8c5c48632c5fb79d3b7: passed.
    0x63a3cc83fd1ec1b6680e9974a0514e1a9ecebb6a: passed.
    0x875a90909a8afc92fb7070047e9d081ec92f3d08b8: passed.
    0x444b25f9c9259dc217772cc4478c44b6feff62353673: passed.
    0x487351c8a5f440e4d03386483d5fe7bb669d41adcbfdb7: passed.
    0x46b061ef132b87f6d3b0ee2462f67d910977da20aed13705: passed.
    0x3842b6137bb9d27f3ca5bafe5bbb62858344fe4ba5c41589a5: passed.
    0x44d91d3d465a4111462ba0c7ec223da6735f4f5200453cf132c3: FAILED. Expected: "c2ff7ccde143c8f0601f6974b1903eb8d5741b6e"; got: "3d1a8f34af592983c30453c028f7f32f319c7f87"
    0xcce73f2eabcb52f785d5a6df63c0a105f34a91ca237fe534ee399d: passed.
    0x664e6e7946839203037a65a12174b244de8cbc6ec3f578967a84f9ce: passed.
    0x9597f714b2e45e3399a7f02aec44921bd78be0fefee0c5e9b499488f6e: passed.
    0x75c5ad1f3cbd22e8a95fc3b089526788fb4ebceed3e7d4443da6e081a35e: passed.
    0xdd245bffe6a638806667768360a95d0574e1a0bd0d18329fdb915ca484ac0d: passed.
    0x0321794b739418c24e7c2e565274791c4be749752ad234ed56cb0a6347430c6b: passed.
    0x4c3dcf95c2f0b5258c651fcd1d51bd10425d6203067d0748d37d1340d9ddda7db3: passed.
    0xb8d12582d25b45290a6e1bb95da429befcfdbf5b4dd41cdf3311d6988fa17cec0723: passed.
    0x6fda97527a662552be15efaeba32a3aea4ed449abb5c1ed8d9bfff544708a425d69b72: passed.
    0x09fa2792acbb2417e8ed269041cc03c77006466e6e7ae002cf3f1af551e8ce0bb506d705: passed.
    0x5efa2987da0baf0a54d8d728792bcfa707a15798dc66743754406914d1cfe3709b1374eaeb: passed.
    0x2836de99c0f641cd55e89f5af76638947b8227377ef88bfba662e5682babc1ec96c6992bc9a0: passed.
    0x42143a2b9e1d0b354df3264d08f7b602f54aad922a3d63006d097f683dc11b90178423bff2f7fe: FAILED. Expected: "b88fb75274b9b0fd57c0045988cfcef6c3ce6554"; got: "1320e77100a9baa7981300a00f40765b26fc9056"
    0xeb60c28ad8aeda807d69ebc87552024ad8aca68204f1bcd29dc5a81dd228b591e2efb7c4df75ef03: passed.
    0x7de4ba85ec54747cdc42b1f23546b7e490e31280f066e52fac117fd3b0792e4de62d5843ee98c72015: passed.
    0xe70653637bc5e388ccd8dc44e5eace36f7398f2bac993042b9bc2f4fb3b0ee7e23a96439dc01134b8c7d: passed.
    0xdd37bc9f0b3a4788f9b54966f252174c8ce487cbe59c53c22b81bf77621a7ce7616dcb5b1e2ee63c2c309b: passed.
    0x5f485c637ae30b1e30497f0fb7ec364e13c906e2813daa34161b7ac4a4fd7a1bddd79601bbd22cef1f57cbc7: passed.
    0xf6c237fb3cfe95ec8414cc16d203b4874e644cc9a543465cad2dc563488a659e8a2e7c981e2a9f22e5e868ffe1: passed.
    0xda7ab3291553c659873c95913768953c6e526d3a26590898c0ade89ff56fbd110f1436af590b17fed49f8c4b2b1e: passed.
    0x8cfa5fd56ee239ca47737591cba103e41a18acf8e8d257b0dbe8851134a81ff6b2e97104b39b76e19da256a17ce52d: passed.
    0x57e89659d878f360af6de45a9a5e372ef40c384988e82640a3d5e4b76d2ef181780b9a099ac06ef0f8a7f3f764209720: passed.
    0xb91e64235dbd234eea2ae14a92a173ebe835347239cff8b02074416f55c6b60dc6ced06ae9f8d705505f0d617e4b29aef9: passed.
    0xe42a67362a581e8cf3d847502215755d7ad425ca030c4360b0f7ef513e6980265f61c9fa18dd9ce668f38dbc2a1ef8f83cd6: passed.
    0x634db92c22010e1cbf1e1623923180406c515272209a8acc42de05cc2e96a1e94c1f9f6b93234b7f4c55de8b1961a3bf352259: passed.
    0xcc6ca3a8cb391cd8a5aff1faa7b3ffbdd21a5a3ce66cfaddbfe8b179e4c860be5ec66bd2c6de6a39a25622f9f2fcb3fc05af12b5: passed.
    0x7c0e6a0d35f8ac854c7245ebc73693731bbbc3e6fab644466de27bb522fcb99307126ae718fe8f00742e6e5cb7a687c88447cbc961: FAILED. Expected: "6f18190bd2d02fc93bce64756575cea36d08b1c3"; got: "ddb637f5d7cd9ff92e4dd0c11b34b606f707d5e8"
    0xc5581d40b331e24003901bd6bf244aca9e9601b9d81252bb38048642731f1146b8a4c69f88e148b2c8f8c14f15e1d6da57b2daa9991e: passed.
    0xec6b4a88713df27c0f2d02e738b69db43abda3921317259c864c1c386e9a5a3f533dc05f3beeb2bec2aac8e06db4c6cb3cddcf697e03d5: passed.
    0x0321736beba578e90abc1a90aa56157d871618f6de0d764cc8c91e06c68ecd3b9de3824064503384db67beb7fe012232dacaef93a000fba7: FAILED. Expected: "aef843b86916c16f66c84d83a6005d23fd005c9e"; got: "7bbe871e486c6442cb5a246fe88c890f4646c746"
    0xd0a249a97b5f1486721a50d4c4ab3f5d674a0e29925d5bf2678ef6d8d521e456bd84aa755328c83fc890837726a8e7877b570dba39579aabdd: passed.
    0xc32138531118f08c7dcc292428ad20b45ab27d9517a18445f38b8f0c2795bcdfe3ffe384e65ecbf74d2c9d0da88398575326074904c1709ba072: passed.
    0xb0f4cfb939ea785eabb7e7ca7c476cdd9b227f015d905368ba00ae96b9aaf720297491b3921267576b72c8f58d577617e844f9f0759b399c6b064c: FAILED. Expected: "534c850448dd486787b62bdec2d4a0b140a1b170"; got: "efc5525d1350f6247f4e65cd2db1d655d1a48e11"
    0xbd02e51b0cf2c2b8d204a026b41a66fbfc2ac37ee9411fc449c8d1194a0792a28ee731407dfc89b6dfc2b10faa27723a184afef8fd83def858a32d3f: passed.
    0xe33146b83e4bb671392218da9a77f8d9f5974147182fb95ba662cb66011989c16d9af104735d6f79841aa4d1df276615b50108df8a29dbc9de31f4260d: passed.
    0x411c13c75073c1e2d4b1ecf13139ba9656cd35c14201f1c7c6f0eeb58d2dbfe35bfdeccc92c3961cfabb590bc1eb77eac15732fb0275798680e0c7292e50: passed.
    0xf2c76ef617fa2bfc8a4d6bcbb15fe88436fdc2165d3074629579079d4d5b86f5081ab177b4c3f530376c9c924cbd421a8daf8830d0940c4fb7589865830699: passed.
    0x45927e32ddf801caf35e18e7b5078b7f5435278212ec6bb99df884f49b327c6486feae46ba187dc1cc9145121e1492e6b06e9007394dc33b7748f86ac3207cfe: passed.
    at /home/mon/spiseMisu/code/elm-sha/tests/test.js:567:9
    at _elm_community$elm_test$ElmTest_Runner_Console$runDisplay (/home/mon/spiseMisu/code/elm-sha/tests/test.js:7929:9)
    at _elm_community$elm_test$ElmTest_Runner_Console$runSuite (/home/mon/spiseMisu/code/elm-sha/tests/test.js:7944:11)
    at Object.<anonymous> (/home/mon/spiseMisu/code/elm-sha/tests/test.js:9052:8)
    at Object.<anonymous> (/home/mon/spiseMisu/code/elm-sha/tests/test.js:9087:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
mon@razerRamon:~/spiseMisu/code/elm-sha/tests$ 
```

Now I least have the possibility to check if it works as expected.

I would like to thank you for your very helpful feedback. I hope I didn't _ruined_ your weekend and on the positive side, you now have working test cases that comply with `NIST` which might get more people to use your library :+1:

**Comment by gentauro** [comment]
Finally got it to work.

If a `HEX` string is all zeros, then it's just an empty string:

- https://github.com/spisemisu/elm-sha/blob/1.0.4/src/SHA.elm#L744

But now all the test are passing (both Short and Longs `.rsp`):

```
mon@razerRamon:~/spiseMisu/code/elm-sha/tests$ ./run-tests.sh 
Downloading elm-community/elm-test
Downloading elm-lang/core
Downloading elm-lang/html
Downloading elm-lang/virtual-dom
Downloading spisemisu/elm-utf8
Packages configured successfully!
Success! Compiled 47 modules.                                       
Successfully generated test.js
  10 suites run, containing 396 tests
  All tests passed
  

: ""
mon@razerRamon:~/spiseMisu/code/elm-sha/tests$
```

So I think there is no more to do here :+1: 

I will let you have the last word (and I will close the issue).

Once again thank you for your fast aid, it has truly been a pleasure working with you.

**Comment by chrisveness** [comment]
Hmm. I think the `.rsp` files are poorly structured. I would consider `0x00` to be a 1-byte number with value '0' (i.e. length = 8), rather than a zero-length message.

I handled that in the test routine, [github.com/chrisveness/crypto/blob/ddcbb2a/test/sha.js#L36](https://github.com/chrisveness/crypto/blob/ddcbb2a/test/sha.js#L36).

Anyway, glad to hear you've got all your tests running, and indeed, I'm glad to have the extra tests for my code, too.

**Comment by gentauro** [comment]
> Hmm. I think the `.rsp` files are poorly structured. I would consider `0x00` to be a `1-byte` number with value `0` (i.e. length = 8), rather than a zero-length message.

Couldn't agree more.
