### ISSUE TITLE
HMAC

### ISSUE THREAD

**Issue by icidasset** [spisemisu/elm-sha#2]
Hi again!

This may or may not be a bug, or maybe it's a feature, I don't know.
I'm working on HMAC implementation for Elm and I was running into a weird situation.
My implementation is something like this:

```elm
hasher =
            SHA.sha256sum

message
            |> String.append partOne -- i_pad
            |> hasher
            |> hexStringToUtf8String
            |> String.append partTwo -- o_pad
            |> hasher
```

Which doesn't give me a valid HMAC.
But if I do the following, it does:

```elm
message
            |> String.append partOne -- i_pad
            |> hasher
            |> String.append ("0x" ++ utf8StringToHexString partTwo) -- o_pad
            |> hasher
```

__That is, when I take the output of your `SHA.sha256sum` function, add another string to it and run it through `SHA.sha256sum` again as string, it doesn't give me a valid HMAC, but when I pass it as a hex-encoded string, then it does give me a valid HMAC.__

I have no clue what the reason might be for this. Do you?
Is it because of this line https://github.com/spisemisu/elm-sha/blob/343a0a7c86ed7d94823fbeab90708e5d7e95e009/src/SHA.elm#L730?

Thanks ☺️ 

PS. You can find the code here: https://github.com/icidasset/ongaku-ryoho/blob/hmac-refactor/src/App/Sources/Crypto/Hmac.elm

**Comment by gentauro** [comment]
Hi @icidasset 

This is actually intentional, see change request ` Added NIST test cases to ensure correctness`:

- https://github.com/spisemisu/elm-sha/commit/000147c278eee1f01f30d9e0d503bc1c26e17b88#diff-99db4324ea06e589e0e8611cc5aae3a4R124

I found out that in order to handle `sha256sum` correctly with the official `NIST test cases` i have to handle `hexadecimal` numbers like that.

But I can see that it's a annoying to do what you do. Could you solve it by creating a `prime` `sha256sum` that does what you are looking for?

> Note: I will try to do it on my `*nix` box to see what happens. This time I'm probably not going to do it as fast as last time :+1: (but you never know)

**Comment by icidasset** [comment]
Thanks!

Yeah, the hexadecimal-number handling is great, it works as expected 👍 I'm just failing to understand why that I'm getting a different result (ie. from `sha256sum`) if I'm just passing the same thing as a string?

That is:

```
string
  |> SHA.sha256sum
  |> String.append ("0x" ++ utf8StringtoHexString "anotherString")
  |> SHA.sha256sum
```

☝️ The above works as expected (ie. passing a hex-encoded string)

```
string
  |> SHA.sha256sum
  |> hexStringToUtf8String
  |> String.append "anotherString"
  |> SHA.sha256sum
```

☝️ While this doesn't (ie. passing a UTF-8 string).

I hope this makes it a bit easier to understand 😳 
By the way, what do you mean by `prime sha256sum`?

**Comment by gentauro** [comment]
Hi @icidasset.

I have executed the following on my `*nix` box:
```bash
mon@razerRamon:~/tmp$ echo -n 'foo' | sha256sum
2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae  -
mon@razerRamon:~/tmp$ echo -n '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae' | sha256sum 
505221025f9701f8a05cc22cbafeec897598b2924a9d665cbc10f0073d66da20  -
mon@razerRamon:~/tmp$ 
```

Then I have executed the following in `Elm`:
```elm
module Main exposing (main)

import Html exposing (Html, text)
import SHA exposing (..)

main : Html msg
main =
    text <| toString <| SHA.sha256sum <| SHA.sha256sum "foo"
```

producing the following output:
```text
"505221025f9701f8a05cc22cbafeec897598b2924a9d665cbc10f0073d66da20"
```

I'm guessing it works as it should right?

**Comment by gentauro** [comment]
Btw, where have you found `hexStringToUtf8String` and `utf8StringtoHexString`?

**Comment by icidasset** [comment]
Yeah, that's the hex-encoded string that I was talking about, which works great 👍 
The problem I'm having is:

```shell
~ echo -n 'foo' | sha256sum | convertToUtf8String | sha256sum
# The result of this should be the same as what you got, but it isn't
```

Those hex-conversion functions are something I wrote myself (partially).
https://github.com/icidasset/ongaku-ryoho/blob/hmac-refactor/src/App/Sources/Crypto/Hex.elm

**Comment by gentauro** [comment]
You know that from the `terminal` if you write this:
```bash
mon@razerRamon:~/tmp$ echo -n 'foo' | sha256sum | sha256sum 
ba2ee357d4b986d003dd0a077c2f80c82f15f7eebb151126561ff599c4a45343  -
```

You don't get the same result right? Output from `sha256sum` has a trailing `-` which is fed to the next pipe. This is actually incorrect. That's why I have made it in two steps:
```bash
mon@razerRamon:~/tmp$ echo -n 'foo' | sha256sum
2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae  -
mon@razerRamon:~/tmp$ echo -n '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae' | sha256sum 
505221025f9701f8a05cc22cbafeec897598b2924a9d665cbc10f0073d66da20  -
```

**Comment by icidasset** [comment]
Oh ok, I didn't notice that, sorry about that.
Well, in any case, you know what I mean, I hope.
Tell me if I'm not making any sense 😳

**Comment by gentauro** [comment]
Sure, I might try to run your code tomorrow. Right now I'm watching some football :+1: (Real fan)

**Comment by icidasset** [comment]
Thanks! Sorry for the trouble.
Enjoy the football 😄

**Comment by gentauro** [comment]
Hi @icidasset 

I have written the following code:
```elm
module Main exposing (main)

import Char exposing (..)
import Html exposing (Html, text)
import SHA exposing (..)
import String exposing (..)

stringify : KeyCode -> String
stringify =
    fromCode >> fromChar

hexToString : String -> String
hexToString hex =
    -- Take chunks of 2 hex digits and apply formula: (a * 16^1) + (b * 16^0)
    -- Example (d_16 = 13_10): 0xd3 => (d * 16^1) + (3 * 16^0) = 208 + 3 = 211
    let
        zero =
            hex |> String.all (\c -> c == '0')

        asciiToNumber x =
            let
                y =
                    x |> Char.toCode
            in
                case y > 96 of
                    -- ASCII codes for [a-f] => [97-102]
                    True ->
                        y - 97 + 10

                    -- ASCII codes for [0-9] => [48-57]
                    False ->
                        y - 48

        rec xs acc =
            case xs == "" of
                False ->
                    let
                        ( y, ys ) =
                            case String.uncons xs of
                                Nothing ->
                                    ( Nothing, "" )

                                Just ( a, rest ) ->
                                    ( Just a, rest )

                        ( z, zs ) =
                            case String.uncons ys of
                                Nothing ->
                                    ( Nothing, "" )

                                Just ( b, rest ) ->
                                    ( Just b, rest )

                        keyCode =
                            case ( y, z ) of
                                ( Just a, Just b ) ->
                                    ((asciiToNumber a) * 16)
                                        + (asciiToNumber b)

                                ( Just a, _ ) ->
                                    (asciiToNumber a) * 16

                                ( _, _ ) ->
                                    0
                    in
                        rec zs (acc ++ (keyCode |> stringify))

                True ->
                    acc
    in
        case zero of
            True ->
                ""

            False ->
                rec (hex |> String.toLower) ""

foo : String
foo =
    "foo"
    |> SHA.sha256sum
    |> hexToString
    |> String.append "anotherString"
    |> SHA.sha256sum
    

main : Html msg
main =
    text <| foo
```
with the following output
```text
a6b3d34a6a7a12cfa345e3095e49e8dde76fdd53c79afe1cea9bbbc152f214e8
```
I have taken `hexToString` (not exposed from the module) from `elm-sha`:

- https://github.com/spisemisu/elm-sha/blob/sync/src/SHA.elm#L733-L734

As you don't have posted any results I don't know if I'm getting the same value as you are but I can see that I get the same values as `hexStringToUtf8String`:

- https://github.com/icidasset/ongaku-ryoho/blob/hmac-refactor/src/App/Sources/Crypto/Hex.elm#L17-L18

So what comes to mind it that in:
```elm
string
  |> SHA.sha256sum
  |> hexStringToUtf8String
  |> String.append "anotherString"
  |> SHA.sha256sum
```
You are combining combining a _**JavaScript**_ `string` with an _**UTF-8**_ `string`. I'm not a `JS` expert, but I don't think that `strings` are `UTF-8` by default. Otherwise we wouldn't use all the effort in making these kind of libraries:

- http://package.elm-lang.org/packages/elm-lang/core/5.1.1/String

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

As `sha256sum` handles `all` elements of the string as if it was of a given type, ex: `utf8` or `hex`, then it's when you will have some problems ...

So I'm guessing the right approach, is to convert `whatever` (`unicode`,`utf8`, ...) you are going to append to your `hex` and from that point `sha256sum` again. Then you will now that `all` elements in your string are of a given type (`hex`), therefore `sha256sum` should work as expected. And that it's what you are doing here:

```elm
string
  |> SHA.sha256sum
  |> String.append ("0x" ++ utf8StringtoHexString "anotherString")
  |> SHA.sha256sum
```

So I guess you will need to stick with that approach :+1: 

> **Note:** Have you tried to create a mixture of Unicode, UTF-8, HEX and feed it to your `sha256sum` in your terminal? I guess you will have the same value as you are getting with this library. Just an assumption.

**Comment by icidasset** [comment]
Thanks for helping me figure this out, I really appreciate it ☺️ 

(1)
I got the same output (ie. `a6b3d34a6a7a12cfa345e3095e49e8dde76fdd53c79afe1cea9bbbc152f214e8`)

(2)
Yeah, I'm a bit confused by the usage of unicode & utf-8.  Actually, now that I think about it, my `utf8StringtoHexString` actually returns unicode, not utf-8 (`Char.fromCode` uses [`String.fromCharCode`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode) from the js stdlib, which returns unicode).

(3)
I would stick with my current approach if I didn't want to support other hashing algorithms. I think your library is the only one that allows hex-encoded strings 😞  So this approach would only work with your library (at this moment).

__Anyhow, I'm just really curious to why passing a unicode string doesn't work.__ Is it because you convert it to utf-8 [here](https://github.com/spisemisu/elm-sha/blob/343a0a7c86ed7d94823fbeab90708e5d7e95e009/src/SHA.elm#L730)? The other case-statement item (ie. `hexToString (String.dropLeft 2 str)`) doesn't get converted to utf-8 though, so maybe that's the difference/issue?

**Comment by gentauro** [comment]
I'm guessing that my `shaXXXsum` only support `hex` and `unicode`:

> This is a port to Elm of (c) Chris Veness library to encode / decode between multi-byte Unicode characters and UTF-8 multiple single-byte character encoding.

Taken from:

- https://github.com/spisemisu/elm-utf8

So if you want to be on the safe side, you might as well just convert it all to `unicode`.

You can see how I feed a list of `hashes` to my `merkle trees`:

- https://github.com/spisemisu/elm-merkletree/blob/sync/tests/Test/Merkle.elm#L60-L69

I can give it my `sha256sum` or just pass the `identity` function (`a -> a`). Or I could add both. As I recall, I'm assuming that the given `JSON string` is actually `unicode` (multi-byte) which will be converted to `utf8` (single-byte).

As I stated before, the reason I needed to introduce the extra `hex` branch, was to be able to comply with the `NIST test cases` so I probably not going to change anything :+1:

**Comment by icidasset** [comment]
Thanks Ramón! I owe you one 👍
